export default {
    DO_LOGIN: "DO_LOGIN",

    UPDATE_WORKFLOW: "UPDATE_WORKFLOW",
    SAVE_WORKFLOW: "SAVE_WORKFLOW",
    RESET_WORKFLOW: "RESET_WORKFLOW",


    GO_TO: 'GO_TO',
    UPDATE_LIST: 'UPDATE_LIST',
    UPDATE_COMPLETE_LIST: 'UPDATE_COMPLETE_LIST'
}